export const APIMAP = {
	// 首页
	homes: "homes",
	// 首页搜索关键词
	searchAll: "search_all",
	// 获取店铺信息
	shopDp: "shop_dp",
	// 获取店铺分类信息
	getShopfl: "get_shopfl",
	// 获取导览信息
	dlList: "dl_list",
	// 获取楼栋信息
	getLodun: "get_lodun",
	// 获取楼层信息
	getFllor: "get_fllor",
	// 获取服务信息
	fwList: "fw_list",
	// 获取服务分类信息
	fwflList: "fw_fl_list",
	// 意见反馈
	yjFeeback: "yj_feeback",
	// 反馈列表或查看详情
	feebackList: "feeback_list",
	// 关于我们
	aboutMyself: "about_myself",
	// 登录
	LoginsUserLogin: "Logins/user_login",
	// 获取openId
	LoginsGetOpendId: "Logins/getOpendId"
}